### PR TITLE
added new chapter about creating tables, and applied minor edits to r…

### PR DESCRIPTION
**Pull request by csobier**
…elated section

For [Docs issue#1175](https://github.com/CartoDB/docs/issues/1175)

@rochoa , please review and let me know if you have any edits, or if I can merge?

### CODE REVIEW

**Comment by csobier** [comment]
@rochoa , do you approve?

**Comment by csobier** [comment]
@namessanti , this content was already approved to be added to the docs by @rochoa (from the original support [issue](https://github.com/CartoDB/docs/issues/1175) on 15th, February 2017). 

This PR is just a courtesy to confirm that everything looks correct (which I can certify, since I worked with Support to create this content). I'm going to go ahead an merge. Sound good?

**Comment by namessanti** [comment]
Per my discussion with @rochoa We're closing this issue to remove clutter until docs are updated.

**Comment by inigomedina** [comment]
We are still with the same library. Sure we are going to change it for better. But right now it has sense to add this kind of documentation improvements.

**Pull request merged**
