### PR TITLE
added link to creating indexes section

### PR DESCRIPTION
**Pull request by csobier**
In regards to [Docs issue#446](https://github.com/CartoDB/docs/issues/446).

@matallo , please merge.  All I did was add a hyperlink to related content.

### CODE REVIEW

**Comment by matallo** [comment]
:sparkles:

**Comment by csobier** [comment]
@matallo , the merge from ago is still not appearing live?

**Comment by matallo** [comment]
oop, it was done to master, https://github.com/CartoDB/CartoDB-SQL-API/pull/258 isn't reviewed yet (where the current docs are)

/cc @rochoa

**Comment by csobier** [comment]
:+1: See it now

**Pull request merged**
