### PR TITLE
Update cartodb-psql

### PR DESCRIPTION
**Pull request by rafatower**

### CODE REVIEW

**Comment by dgaubert** [comment]
Heads up! From now on you need to update packages using `npm` to make `package-lock.json` aware of that:
  - `npm remove cartodb-psql && npm install cartodb-psql@0.13.1` does the trick.

In projects where we support `yarn.lock` we need to sync both `package-lock.json` and `yarn.lock` before I finish the transition to `npm` everywhere:
  - `yarn import` 

More info [here](https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/)

**Comment by rafatower** [comment]
thanks! I was reading through the docs and also noticed your node 10 changes :)
you saved me some research time, thanks

**Comment by dgaubert** [comment]
I've just updated the comment. I missed an important step. :)

**Comment by rafatower** [comment]
@dgaubert may I have your blessing? :smiley:

**Pull request merged**
